#pragma once

#include <cstdint>

#pragma pack(push, 1)
// TGA Table Param values
struct EffectData
{
	int32_t iconId;
	float conditionHp;
	float effectEndurance;
	float motionInterval;
	float maxHpRate;
	float maxMpRate;
	float maxStaminaRate;
	float slashDamageCutRate;
	float blowDamageCutRate;
	float thrustDamageCutRate;
	float neutralDamageCutRate;
	float magicDamageCutRate;
	float fireDamageCutRate;
	float thunderDamageCutRate;
	float physicsAttackRate;
	float magicAttackRate;
	float fireAttackRate;
	float thunderAttackRate;
	float physicsAttackPowerRate;
	float magicAttackPowerRate;
	float fireAttackPowerRate;
	float thunderAttackPowerRate;
	int32_t physicsAttackPower;
	int32_t magicAttackPower;
	int32_t fireAttackPower;
	int32_t thunderAttackPower;
	float physicsDiffenceRate;
	float magicDiffenceRate;
	float fireDiffenceRate;
	float thunderDiffenceRate;
	int32_t physicsDiffence;
	int32_t magicDiffence;
	int32_t fireDiffence;
	int32_t thunderDiffence;
	float NoGuardDamageRate;
	float vitalSpotChangeRate;
	float normalSpotChangeRate;
	float lookAtTargetPosOffset;
	int32_t behaviorId;
	float changeHpRate;
	int32_t changeHpPoint;
	float changeMpRate;
	int32_t changeMpPoint;
	int32_t mpRecoverChangeSpeed;
	float changeStaminaRate;
	int32_t changeStaminaPoint;
	int32_t staminaRecoverChangeSpeed;
	float magicEffectTimeChange;
	int32_t insideDurability;
	int32_t maxDurability;
	float staminaAttackRate;
	int32_t poizonAttackPower;
	int32_t diseaseAttackPower;
	int32_t bloodAttackPower;
	int32_t curseAttackPower;
	float fallDamageRate;
	float soulRate;
	float equipWeightChangeRate;
	float allItemWeightChangeRate;
	int32_t soul;
	int32_t animIdOffset;
	float haveSoulRate;
	float targetPriority;
	int32_t sightSearchEnemyRate;
	float hearingSearchEnemyRate;
	float grabityRate;
	float registPoizonChangeRate;
	float registDiseaseChangeRate;
	float registBloodChangeRate;
	float registCurseChangeRate;
	float soulStealRate;
	float lifeReductionRate;
	float hpRecoverRate;
	int32_t replaceSpEffectId;
	int32_t cycleOccurrenceSpEffectId;
	int32_t atkOccurrenceSpEffectId;
	float guardDefFlickPowerRate;
	float guardStaminaCutRate;
	int16_t rayCastPassedTime;
	int16_t changeSuperArmorPoint;
	int16_t bowDistRate;
	int16_t spCategory;
	int8_t categoryPriority;
	int8_t saveCategory;
	uint8_t changeMagicSlot;
	uint8_t changeMiracleSlot;
	uint8_t heroPointDamage;
	uint8_t defFlickPower;
	uint8_t flickDamageCutRate;
	uint8_t bloodDamageRate;
	uint8_t dmgLv_None;
	uint8_t dmgLv_S;
	uint8_t dmgLv_M;
	uint8_t dmgLv_L;
	uint8_t dmgLv_BlowM;
	uint8_t dmgLv_Push;
	uint8_t dmgLv_Strike;
	uint8_t dmgLv_BlowS;
	uint8_t dmgLv_Min;
	uint8_t dmgLv_Uppercut;
	uint8_t dmgLv_BlowLL;
	uint8_t dmgLv_Breath;
	uint8_t atkAttribute;
	uint8_t spAttribute;
	int16_t stateInfo;
	uint8_t wepParamChange;
	uint8_t moveType;
	int16_t lifeReductionType;
	uint8_t throwCondition;
	int8_t addBehaviorJudgeId_condition;
	uint8_t freezeDamageRate;
	uint8_t effectTargetSelf : 1;
	uint8_t effectTargetFriend : 1;
	uint8_t effectTargetEnemy : 1;
	uint8_t effectTargetPlayer : 1;
	uint8_t effectTargetAI : 1;
	uint8_t effectTargetLive : 1;
	uint8_t effectTargetGhost : 1;
	uint8_t effectTargetWhiteGhost : 1;
	uint8_t effectTargetBlackGhost : 1;
	uint8_t effectTargetAttacker : 1;
	uint8_t dispIconNonactive : 1;
	uint8_t useSpEffectEffect : 1;
	uint8_t bAdjustMagicAbility : 1;
	uint8_t bAdjustFaithAbility : 1;
	uint8_t bGameClearBonus : 1;
	uint8_t magParamChange : 1;
	uint8_t miracleParamChange : 1;
	uint8_t clearSoul : 1;
	uint8_t requestSOS : 1;
	uint8_t requestBlackSOS : 1;
	uint8_t requestForceJoinBlackSOS : 1;
	uint8_t requestKickSession : 1;
	uint8_t requestLeaveSession : 1;
	uint8_t requestNpcInveda : 1;
	uint8_t noDead : 1;
	uint8_t bCurrHPIndependeMaxHP : 1;
	uint8_t corrosionIgnore : 1;
	uint8_t sightSearchCutIgnore : 1;
	uint8_t hearingSearchCutIgnore : 1;
	uint8_t antiMagicIgnore : 1;
	uint8_t fakeTargetIgnore : 1;
	uint8_t fakeTargetIgnoreUndead : 1;
	uint8_t fakeTargetIgnoreAnimal : 1;
	uint8_t grabityIgnore : 1;
	uint8_t disablePoison : 1;
	uint8_t disableDisease : 1;
	uint8_t disableBlood : 1;
	uint8_t disableCurse : 1;
	uint8_t enableCharm : 1;
	uint8_t enableLifeTime : 1;
	uint8_t hasTarget : 1;
	uint8_t replanningOnFire : 1;
	uint8_t eraseOnBonfireRecover : 1;
	uint8_t requestLeaveColiseumSession : 1;
	uint8_t bAdjustStrengthAblity : 1;
	uint8_t bAdjustAgilityAblity : 1;
	uint8_t chargeAttackParamChange : 1;
	uint8_t throwAttackParamChange : 1;
	uint8_t vowType0 : 1;
	uint8_t vowType1 : 1;
	uint8_t vowType2 : 1;
	uint8_t vowType3 : 1;
	uint8_t vowType4 : 1;
	uint8_t vowType5 : 1;
	uint8_t vowType6 : 1;
	uint8_t vowType7 : 1;
	uint8_t vowType8 : 1;
	uint8_t vowType9 : 1;
	uint8_t vowType10 : 1;
	uint8_t vowType11 : 1;
	uint8_t vowType12 : 1;
	uint8_t vowType13 : 1;
	uint8_t vowType14 : 1;
	uint8_t vowType15 : 1;
	uint8_t repAtkDmgLv;
	float sightSearchRate;
	uint8_t effectTargetOpposeTarget : 1;
	uint8_t effectTargetFriendlyTarget : 1;
	uint8_t effectTargetSelfTarget : 1;
	uint8_t effectTargetPcHorse : 1;
	uint8_t effectTargetPcDeceased : 1;
	uint8_t isContractSpEffectLife : 1;
	uint8_t isWaitModeDelete : 1;
	uint8_t isIgnoreNoDamage : 1;
	int8_t changeTeamType;
	int16_t dmypolyId;
	int32_t vfxId;
	int32_t accumuOverFireId;
	int32_t accumuOverVal;
	int32_t accumuUnderFireId;
	int32_t accumuUnderVal;
	int32_t accumuVal;
	uint8_t eye_angX;
	uint8_t eye_angY;
	int16_t addDeceasedLv;
	int32_t unknown;
	int32_t vfxId1;
	int32_t vfxId2;
	int32_t vfxId3;
	int32_t vfxId4;
	int32_t vfxId5;
	int32_t vfxId6;
	int32_t vfxId7;
	int32_t freezeAttackPower;
	int32_t AppearAiSoundId;
	int16_t addFootEffectSfxId;
	int8_t unknown2;
	int8_t teamOffenseEffectivity;
	float toughnessDamageCutRate;
	float weakDmgRateA;
	float weakDmgRateB;
	float weakDmgRateC;
	float weakDmgRateD;
	float weakDmgRateE;
	float weakDmgRateF;
	float darkDamageCutRate;
	float darkDiffenceRate;
	int32_t darkDiffence;
	float darkAttackRate;
	float darkAttackPowerRate;
	int32_t darkAttackPower;
	float antiDarkSightRadius;
	int32_t antiDarkSightDmypolyId;
	float conditionHpRate;
	float consumeStaminaRate;
	float itemDropRate;
	float unknown3;
	int32_t changePoisonResistPoint;
	int32_t changeDiseaseResistPoint;
	int32_t changeBloodResistPoint;
	int32_t changeCurseResistPoint;
	int32_t changeFreezeResistPoint;
	float slashAttackRate;
	float blowAttackRate;
	float thrustAttackRate;
	float neutralAttackRate;
	float slashAttackPowerRate;
	float blowAttackPowerRate;
	float thrustAttackPowerRate;
	float neutralAttackPowerRate;
	int32_t slashAttackPower;
	int32_t blowAttackPower;
	int32_t thrustAttackPower;
	int32_t neutralAttackPower;
	int32_t changeStrengthPoint;
	int32_t changeAgilityPoint;
	int32_t changeMagicPoint;
	int32_t changeFaithPoint;
	int32_t changeLuckPoint;
	int8_t recoverArtsPoint_Str;
	int8_t recoverArtsPoint_Dex;
	int8_t recoverArtsPoint_Magic;
	int8_t recoverArtsPoint_Miracle;
	uint8_t wetConditionDepth;
	uint8_t disableFreeze : 1;
	uint8_t isUseStatusAilmentAtkPowerCorrect : 1;
	uint8_t isUseAtkParamAtkPowerCorrect : 1;
	uint8_t isHollowingCorrection : 1;
	uint8_t affectedByDurationContraction : 1;
	uint8_t waitForTriggerStateInfo : 1;
	uint8_t ignoreNoDamage : 1;
	uint8_t isDisableNetSync : 1;
	uint8_t eyeAngleUpper_around;
	uint8_t eyeAngleUpper_bottom;
	float saReceiveDamageRate;
	float defPlayerDmgCorrectRate_Physics;
	float defPlayerDmgCorrectRate_Magic;
	float defPlayerDmgCorrectRate_Fire;
	float defPlayerDmgCorrectRate_Thunder;
	float defPlayerDmgCorrectRate_Dark;
	float defEnemyDmgCorrectRate_Physics;
	float defEnemyDmgCorrectRate_Magic;
	float defEnemyDmgCorrectRate_Fire;
	float defEnemyDmgCorrectRate_Thunder;
	float defEnemyDmgCorrectRate_Dark;
	float defObjDmgCorrectRate;
	float atkPlayerDmgCorrectRate_Physics;
	float atkPlayerDmgCorrectRate_Magic;
	float atkPlayerDmgCorrectRate_Fire;
	float atkPlayerDmgCorrectRate_Thunder;
	float atkPlayerDmgCorrectRate_Dark;
	float atkEnemyDmgCorrectRate_Physics;
	float atkEnemyDmgCorrectRate_Magic;
	float atkEnemyDmgCorrectRate_Fire;
	float atkEnemyDmgCorrectRate_Thunder;
	float atkEnemyDmgCorrectRate_Dark;
	float registFreezeChangeRate;
	int16_t invocationConditionsStateChange1;
	int16_t invocationConditionsStateChange2;
	int16_t invocationConditionsStateChange3;
	uint8_t affectPyromancy;
	uint8_t fakeDexterity_castSpeed;
	float value_Magnification;
	float artsConsumptionRate;
	float magicConsumptionRate;
	float shamanConsumptionRate;
	float miracleConsumptionRate;
	int32_t changeHpEstusFlaskRate;
	int32_t changeHpEstusFlaskPoint;
	int32_t changeMpEstusFlaskRate;
	int32_t changeMpEstusFlaskPoint;
	float changeHpEstusFlaskCorrectRate;
	float changeMpEstusFlaskCorrectRate;
	int32_t applyIdOnGetSoul;
	float extendLifeRate;
	float contractLifeRate;
	uint8_t behaviorJudgeId_add0;
	uint8_t behaviorJudgeId_add1;
	int16_t effectEndDeleteDecalGroupId;
	float defObjectAttackPowerRate;
	int8_t addLifeForceStatus;
	int8_t addWillpowerStatus;
	int8_t addEndureStatus;
	int8_t addVitalityStatus;
	int8_t addStrengthStatus;
	int8_t addDexterityStatus;
	int8_t addMagicStatus;
	int8_t addFaithStatus;
	int8_t addLuckStatus;
	int8_t deleteCriteriaDamage;
	int8_t pad10[14];
};

struct VFXResource
{
	uint64_t vfxID;
	uintptr_t pointer;
	bool success : 1;
};

struct GameEffectData
{
    int32_t effectID;
    int32_t value{ -1 };
	EffectData* effectData;
	int8_t result;
};

#pragma pack(pop)
static_assert(sizeof(EffectData) == 0x320, "Size mismatch!");
static_assert(sizeof(GameEffectData) == 0x11, "Size mismatch!");

struct Effect {
	int32_t effectID;
    EffectData data;
};

const int g_SimpleEffectR = 60;
const int g_SimpleEffectL = 5840;

const int g_CrystalR = 90013120;
const int g_CrystalL = 91011261;

const int g_FireR = 62;
const int g_FireL = 5562;

const int g_LightningR = 151;
const int g_LightningL = 5651;

const int g_DarkR = 5150;
const int  g_DarkL = 5850;

const int g_PoisonEffectR = 152;
const int g_PoisonEffectL = 5652;

const int g_BloodEffectR = 5160;
const int g_BloodEffectL = 5860;

const int g_BlessedR = 90037600;
const int g_BlessedL = 91062751;