#pragma once

#include <cstdint>

#pragma pack(push, 1)
// TGA Table Param values
struct EffectData {
	int32_t iconId;
	float conditionHp;
	float effectEndurance;
	float motionInterval;
	float maxHpRate;
	float maxMpRate;
	float maxStaminaRate;
	float slashDamageCutRate;
	float blowDamageCutRate;
	float thrustDamageCutRate;
	float neutralDamageCutRate;
	float magicDamageCutRate;
	float fireDamageCutRate;
	float thunderDamageCutRate;
	float physicsAttackRate;
	float magicAttackRate;
	float fireAttackRate;
	float thunderAttackRate;
	float physicsAttackPowerRate;
	float magicAttackPowerRate;
	float fireAttackPowerRate;
	float thunderAttackPowerRate;
	int32_t physicsAttackPower;
	int32_t magicAttackPower;
	int32_t fireAttackPower;
	int32_t thunderAttackPower;
	float physicsDiffenceRate;
	float magicDiffenceRate;
	float fireDiffenceRate;
	float thunderDiffenceRate;
	int32_t physicsDiffence;
	int32_t magicDiffence;
	int32_t fireDiffence;
	int32_t thunderDiffence;
	float NoGuardDamageRate;
	float vitalSpotChangeRate;
	float normalSpotChangeRate;
	float lookAtTargetPosOffset;
	int32_t behaviorId;
	float changeHpRate;
	int32_t changeHpPoint;
	float changeMpRate;
	int32_t changeMpPoint;
	int32_t mpRecoverChangeSpeed;
	float changeStaminaRate;
	int32_t changeStaminaPoint;
	int32_t staminaRecoverChangeSpeed;
	float magicEffectTimeChange;
	int32_t insideDurability;
	int32_t maxDurability;
	float staminaAttackRate;
	int32_t poizonAttackPower;
	int32_t diseaseAttackPower;
	int32_t bloodAttackPower;
	int32_t curseAttackPower;
	float fallDamageRate;
	float soulRate;
	float equipWeightChangeRate;
	float allItemWeightChangeRate;
	int32_t soul;
	int32_t animIdOffset;
	float haveSoulRate;
	float targetPriority;
	float sightSearchEnemyRate;
	float hearingSearchEnemyRate;
	float grabityRate;
	float registPoizonChangeRate;
	float registDiseaseChangeRate;
	float registBloodChangeRate;
	float registCurseChangeRate;
	float soulStealRate;
	float lifeReductionRate;
	float hpRecoverRate;
	int32_t replaceSpEffectId;
	int32_t cycleOccurrenceSpEffectId;
	int32_t atkOccurrenceSpEffectId;
	float guardDefFlickPowerRate;
	float guardStaminaCutRate;
	int16_t rayCastPassedTime;
	uint8_t magicSubCategoryChange1;
	uint8_t magicSubCategoryChange2;
	int16_t bowDistRate;
	uint16_t spCategory;
	uint8_t categoryPriority;
	int8_t saveCategory;
	uint8_t changeMagicSlot;
	uint8_t changeMiracleSlot;
	int8_t heroPointDamage;
	uint8_t defFlickPower;
	uint8_t flickDamageCutRate;
	uint8_t bloodDamageRate;
	int8_t dmgLv_None;
	int8_t dmgLv_S;
	int8_t dmgLv_M;
	int8_t dmgLv_L;
	int8_t dmgLv_BlowM;
	int8_t dmgLv_Push;
	int8_t dmgLv_Strike;
	int8_t dmgLv_BlowS;
	int8_t dmgLv_Min;
	int8_t dmgLv_Uppercut;
	int8_t dmgLv_BlowLL;
	int8_t dmgLv_Breath;
	uint8_t atkAttribute;
	uint8_t spAttribute;
	uint16_t stateInfo;
	uint8_t wepParamChange;
	uint8_t moveType;
	uint16_t lifeReductionType;
	uint8_t throwCondition;
	int8_t addBehaviorJudgeId_condition;
	uint8_t freezeDamageRate;
	uint8_t effectTargetSelf : 1;
	uint8_t effectTargetFriend : 1;
	uint8_t effectTargetEnemy : 1;
	uint8_t effectTargetPlayer : 1;
	uint8_t effectTargetAI : 1;
	uint8_t effectTargetLive : 1;
	uint8_t effectTargetGhost : 1;
	uint8_t disableSleep : 1;
	uint8_t disableMadness : 1;
	uint8_t effectTargetAttacker : 1;
	uint8_t dispIconNonactive : 1;
	uint8_t regainGaugeDamage : 1;
	uint8_t bAdjustMagicAblity : 1;
	uint8_t bAdjustFaithAblity : 1;
	uint8_t bGameClearBonus : 1;
	uint8_t magParamChange : 1;
	uint8_t miracleParamChange : 1;
	uint8_t clearSoul : 1;
	uint8_t requestSOS : 1;
	uint8_t requestBlackSOS : 1;
	uint8_t requestForceJoinBlackSOS : 1;
	uint8_t requestKickSession : 1;
	uint8_t requestLeaveSession : 1;
	uint8_t requestNpcInveda : 1;
	uint8_t noDead : 1;
	uint8_t bCurrHPIndependeMaxHP : 1;
	uint8_t corrosionIgnore : 1;
	uint8_t sightSearchCutIgnore : 1;
	uint8_t hearingSearchCutIgnore : 1;
	uint8_t antiMagicIgnore : 1;
	uint8_t fakeTargetIgnore : 1;
	uint8_t fakeTargetIgnoreUndead : 1;
	uint8_t fakeTargetIgnoreAnimal : 1;
	uint8_t grabityIgnore : 1;
	uint8_t disablePoison : 1;
	uint8_t disableDisease : 1;
	uint8_t disableBlood : 1;
	uint8_t disableCurse : 1;
	uint8_t enableCharm : 1;
	uint8_t enableLifeTime : 1;
	uint8_t bAdjustStrengthAblity : 1;
	uint8_t bAdjustAgilityAblity : 1;
	uint8_t eraseOnBonfireRecover : 1;
	uint8_t throwAttackParamChange : 1;
	uint8_t requestLeaveColiseumSession : 1;
	uint8_t isExtendSpEffectLife : 1;
	uint8_t hasTarget : 1;
	uint8_t replanningOnFire : 1;
	uint8_t vowType0 : 1;
	uint8_t vowType1 : 1;
	uint8_t vowType2 : 1;
	uint8_t vowType3 : 1;
	uint8_t vowType4 : 1;
	uint8_t vowType5 : 1;
	uint8_t vowType6 : 1;
	uint8_t vowType7 : 1;
	uint8_t vowType8 : 1;
	uint8_t vowType9 : 1;
	uint8_t vowType10 : 1;
	uint8_t vowType11 : 1;
	uint8_t vowType12 : 1;
	uint8_t vowType13 : 1;
	uint8_t vowType14 : 1;
	uint8_t vowType15 : 1;
	int8_t repAtkDmgLv;
	float sightSearchRate;
	uint8_t effectTargetOpposeTarget : 1;
	uint8_t effectTargetFriendlyTarget : 1;
	uint8_t effectTargetSelfTarget : 1;
	uint8_t effectTargetPcHorse : 1;
	uint8_t effectTargetPcDeceased : 1;
	uint8_t isContractSpEffectLife : 1;
	uint8_t isWaitModeDelete : 1;
	uint8_t isIgnoreNoDamage : 1;
	int8_t changeTeamType;
	int16_t dmypolyId;
	int32_t vfxId;
	int32_t accumuOverFireId;
	int32_t accumuOverVal;
	int32_t accumuUnderFireId;
	int32_t accumuUnderVal;
	int32_t accumuVal;
	uint8_t eye_angX;
	uint8_t eye_angY;
	int16_t addDeceasedLv;
	int32_t vfxId1;
	int32_t vfxId2;
	int32_t vfxId3;
	int32_t vfxId4;
	int32_t vfxId5;
	int32_t vfxId6;
	int32_t vfxId7;
	int32_t freezeAttackPower;
	int32_t AppearAiSoundId;
	int16_t addFootEffectSfxId;
	int8_t dexterityCancelSystemOnlyAddDexterity;
	int8_t teamOffenseEffectivity;
	float toughnessDamageCutRate;
	float weakDmgRateA;
	float weakDmgRateB;
	float weakDmgRateC;
	float weakDmgRateD;
	float weakDmgRateE;
	float weakDmgRateF;
	float darkDamageCutRate;
	float darkDiffenceRate;
	int32_t darkDiffence;
	float darkAttackRate;
	float darkAttackPowerRate;
	int32_t darkAttackPower;
	float antiDarkSightRadius;
	int32_t antiDarkSightDmypolyId;
	float conditionHpRate;
	float consumeStaminaRate;
	float itemDropRate;
	int32_t changePoisonResistPoint;
	int32_t changeDiseaseResistPoint;
	int32_t changeBloodResistPoint;
	int32_t changeCurseResistPoint;
	int32_t changeFreezeResistPoint;
	float slashAttackRate;
	float blowAttackRate;
	float thrustAttackRate;
	float neutralAttackRate;
	float slashAttackPowerRate;
	float blowAttackPowerRate;
	float thrustAttackPowerRate;
	float neutralAttackPowerRate;
	int32_t slashAttackPower;
	int32_t blowAttackPower;
	int32_t thrustAttackPower;
	int32_t neutralAttackPower;
	int32_t changeStrengthPoint;
	int32_t changeAgilityPoint;
	int32_t changeMagicPoint;
	int32_t changeFaithPoint;
	int32_t changeLuckPoint;
	int8_t recoverArtsPoint_Str;
	int8_t recoverArtsPoint_Dex;
	int8_t recoverArtsPoint_Magic;
	int8_t recoverArtsPoint_Miracle;
	uint8_t madnessDamageRate;
	uint8_t isUseStatusAilmentAtkPowerCorrect : 1;
	uint8_t isUseAtkParamAtkPowerCorrect : 1;
	uint8_t dontDeleteOnDead : 1;
	uint8_t disableFreeze : 1;
	uint8_t isDisableNetSync : 1;
	uint8_t shamanParamChange : 1;
	uint8_t isStopSearchedNotify : 1;
	uint8_t isCheckAboveShadowTest : 1;
	uint16_t addBehaviorJudgeId_add;
	float saReceiveDamageRate;
	float defPlayerDmgCorrectRate_Physics;
	float defPlayerDmgCorrectRate_Magic;
	float defPlayerDmgCorrectRate_Fire;
	float defPlayerDmgCorrectRate_Thunder;
	float defPlayerDmgCorrectRate_Dark;
	float defEnemyDmgCorrectRate_Physics;
	float defEnemyDmgCorrectRate_Magic;
	float defEnemyDmgCorrectRate_Fire;
	float defEnemyDmgCorrectRate_Thunder;
	float defEnemyDmgCorrectRate_Dark;
	float defObjDmgCorrectRate;
	float atkPlayerDmgCorrectRate_Physics;
	float atkPlayerDmgCorrectRate_Magic;
	float atkPlayerDmgCorrectRate_Fire;
	float atkPlayerDmgCorrectRate_Thunder;
	float atkPlayerDmgCorrectRate_Dark;
	float atkEnemyDmgCorrectRate_Physics;
	float atkEnemyDmgCorrectRate_Magic;
	float atkEnemyDmgCorrectRate_Fire;
	float atkEnemyDmgCorrectRate_Thunder;
	float atkEnemyDmgCorrectRate_Dark;
	float registFreezeChangeRate;
	uint16_t invocationConditionsStateChange1;
	uint16_t invocationConditionsStateChange2;
	uint16_t invocationConditionsStateChange3;
	int16_t hearingAiSoundLevel;
	float chrProxyHeightRate;
	float addAwarePointCorrectValue_forMe;
	float addAwarePointCorrectValue_forTarget;
	float sightSearchEnemyAdd;
	float sightSearchAdd;
	float hearingSearchAdd;
	float hearingSearchRate;
	float hearingSearchEnemyAdd;
	float value_Magnification;
	float artsConsumptionRate;
	float magicConsumptionRate;
	float shamanConsumptionRate;
	float miracleConsumptionRate;
	int32_t changeHpEstusFlaskRate;
	int32_t changeHpEstusFlaskPoint;
	int32_t changeMpEstusFlaskRate;
	int32_t changeMpEstusFlaskPoint;
	float changeHpEstusFlaskCorrectRate;
	float changeMpEstusFlaskCorrectRate;
	int32_t applyIdOnGetSoul;
	float extendLifeRate;
	float contractLifeRate;
	float defObjectAttackPowerRate;
	int16_t effectEndDeleteDecalGroupId;
	int8_t addLifeForceStatus;
	int8_t addWillpowerStatus;
	int8_t addEndureStatus;
	int8_t addVitalityStatus;
	int8_t addStrengthStatus;
	int8_t addDexterityStatus;
	int8_t addMagicStatus;
	int8_t addFaithStatus;
	int8_t addLuckStatus;
	uint8_t deleteCriteriaDamage;
	uint8_t magicSubCategoryChange3;
	uint8_t spAttributeVariationValue;
	uint8_t atkFlickPower;
	uint8_t wetConditionDepth;
	float changeSaRecoveryVelocity;
	float regainRate;
	float saAttackPowerRate;
	int32_t sleepAttackPower;
	int32_t madnessAttackPower;
	float registSleepChangeRate;
	float registMadnessChangeRate;
	int32_t changeSleepResistPoint;
	int32_t changeMadnessResistPoint;
	uint8_t sleepDamageRate;
	uint8_t applyPartsGroup;
	uint8_t clearTarget : 1;
	uint8_t fakeTargetIgnoreAjin : 1;
	uint8_t fakeTargetIgnoreMirageArts : 1;
	uint8_t requestForceJoinBlackSOS_B : 1;
	uint8_t isDestinedDeathHpMult : 1;
	uint8_t isHpBurnEffect : 1;
	uint8_t unknown_0x352_6 : 1;
	uint8_t unknown_0x352_7 : 1;
	uint8_t unknown_0x353_0 : 1;
	uint8_t unknown_0x353_1 : 1;
	uint8_t unknown_0x353_2 : 1;
	uint8_t unknown_0x353_3 : 1;
	uint8_t unknown_0x353_4 : 1;
	uint8_t unknown_0x353_5 : 3;
	float changeSuperArmorPoint;
	float changeSaPoint;
	float hugeEnemyPickupHeightOverwrite;
	float poisonDefDamageRate;
	float diseaseDefDamageRate;
	float bloodDefDamageRate;
	float curseDefDamageRate;
	float freezeDefDamageRate;
	float sleepDefDamageRate;
	float madnessDefDamageRate;
	uint16_t overwrite_maxBackhomeDist;
	uint16_t overwrite_backhomeDist;
	uint16_t overwrite_backhomeBattleDist;
	uint16_t overwrite_BackHome_LookTargetDist;
	float goodsConsumptionRate;
	float guardStaminaMult;
	int32_t spiritDeathSpEffectId;
};

struct VFXResource
{
	uint64_t vfxID;
	uintptr_t pointer;
	bool success : 1;
};
#pragma pack(pop)
static_assert(sizeof(EffectData) == 0x390, "Size mismatch!");

struct Effect {
	int32_t effectID;
    EffectData data;
};

const int g_FireEffectR = 62;
const int g_FireEffectL = 5100;

//const int g_LightningEffectR = 8720; // alt 8720, 151
const int g_LightningEffectR = 151; // alt 8720, 151
//const int g_LightningEffectL = 8721; // alt 8721, 5105;
const int g_LightningEffectL = 5105; // alt 8721, 5105;

const int g_SacradEffectR = 61;
const int g_SacradEffectL = 5140;

const int g_MagicEffectR = 64;
const int g_MagicEffectL = 5115;

const int g_ColdEffectR = 5092;
const int  g_ColdEffectL = 5135;

const int g_PoisonEffectR = 152;
const int g_PoisonEffectL = 5110;

const int g_BloodEffectR = 5090;
const int g_BloodEffectL = 5125;